### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by ATATC** [ProjectNeura/LEADS#232]
An error was introduced in #230.
